title: But seas between us broad have roared
description: 另一个世界是可能的
author: 鹿角星中继站
avatar: 
email: 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: redwhite

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus

disqus: random-blog-3

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: public/img/icon.jpg
permalink: /:year/:month/:day/:title.html

